name: windows-pyimagej-no-builds
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.13
  - anyio=4.6.2.post1
  - aom=3.9.1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - attrs=24.2.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-blosc2=2.15.1
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.2
  - certifi=2024.8.30
  - cffi=1.17.1
  - charls=2.4.2
  - charset-normalizer=3.4.0
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.12.1
  - dav1d=1.2.1
  - debugpy=1.8.8
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - giflib=5.2.2
  - graphite2=1.3.13
  - h2=4.1.0
  - harfbuzz=10.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - imagecodecs=2024.9.22
  - imageio=2.36.0
  - imglyb=2.1.0
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.2
  - jgo=1.0.6
  - jinja2=3.1.4
  - jpype1=1.5.1
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter_client=7.4.9
  - jupyter_contrib_core=0.4.0
  - jupyter_contrib_nbextensions=0.7.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.6.1
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_widgets=3.0.13
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - labeling=0.1.14
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libaec=1.1.3
  - libavif16=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcups=2.3.3
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.82.2
  - libgomp=14.2.0
  - libhwy=1.1.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libjxl=0.11.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libnsl=2.0.1
  - libopenblas=0.3.28
  - libpng=1.6.44
  - libsodium=1.0.20
  - libsqlite=3.47.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - maven=3.9.9
  - mistune=3.0.2
  - munkres=1.1.4
  - nbclassic=1.1.0
  - nbclient=0.10.0
  - nbconvert=7.16.4
  - nbconvert-core=7.16.4
  - nbconvert-pandoc=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - notebook=6.5.7
  - notebook-shim=0.2.4
  - openjdk=11.0.25
  - openjpeg=2.5.2
  - openssl=3.4.0
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandoc=3.5
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.3.1
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - pooch=1.8.2
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.12.8
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytz=2024.1
  - pywavelets=1.7.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - rav1e=0.6.6
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.21.0
  - scikit-image=0.24.0
  - scipy=1.14.1
  - scyjava=1.10.0
  - send2trash=1.8.3
  - setuptools=75.5.0
  - six=1.16.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.2
  - svt-av1=2.3.0
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241003
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.0
  - widgetsnbextension=4.0.13
  - xarray=2024.10.0
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.21.0
  - zlib-ng=2.2.2
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - aicsimageio==4.14.0
      - aiobotocore==2.5.4
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aioitertools==0.12.0
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - asciitree==0.3.3
      - astunparse==1.6.3
      - bioformats-jar==2020.5.27
      - botocore==1.31.17
      - click==8.1.8
      - cloudpickle==3.1.1
      - csbdeep==0.8.1
      - dask==2025.1.0
      - deprecated==1.2.15
      - distributed==2025.1.0
      - elementpath==4.7.0
      - fasteners==0.19
      - flatbuffers==24.12.23
      - frozenlist==1.5.0
      - fsspec==2023.6.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.69.0
      - h5py==3.12.1
      - jmespath==1.0.1
      - joblib==1.4.2
      - keras==3.8.0
      - libclang==18.1.1
      - llvmlite==0.43.0
      - locket==1.0.0
      - lxml==4.9.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - msgpack==1.1.0
      - multidict==6.1.0
      - namex==0.0.8
      - numba==0.60.0
      - numba-progress==1.1.0
      - numcodecs==0.15.0
      - numpy==1.26.4
      - ome-types==0.5.3
      - ome-zarr==0.10.3
      - opt-einsum==3.4.0
      - optree==0.14.0
      - pandas-flavor==0.6.0
      - partd==1.4.2
      - patsy==1.0.1
      - pingouin==0.5.5
      - propcache==0.2.1
      - protobuf==5.29.3
      - pydantic==2.10.5
      - pydantic-compat==0.1.2
      - pydantic-core==2.27.2
      - pyimagej==1.5.0
      - readlif==0.6.5
      - resource-backed-dask-array==0.1.0
      - rich==13.9.4
      - s3fs==2023.6.0
      - scikit-learn==1.6.1
      - scikit-posthocs==0.11.2
      - seaborn==0.13.2
      - sortedcontainers==2.4.0
      - stardist==0.9.1
      - statannotations==0.7.1
      - statsmodels==0.14.4
      - tabulate==0.9.0
      - tblib==3.0.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.18.0
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tifffile==2023.2.28
      - toolz==1.0.0
      - tqdm==4.67.1
      - urllib3==1.26.20
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xmlschema==3.4.3
      - xsdata==24.3.1
      - yarl==1.18.3
      - zarr==2.15.0
      - zict==3.0.0
