name: CI

on:
  push:
    branches: [tech_dev]
    paths:
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - ".github/workflows/ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello CI"
